export const NOTES = [
  {
    id: 1,
    title: "Mastering Python Basics",
    description:
      "Unlock the power of Python programming with fundamental concepts",
    date: "2023-11-26",
    isDone: false,
  },
  {
    id: 2,
    title: "Data Magic: Lists and Dictionaries",
    description: "Discover the secrets of data structures in Python",
    date: "2023-11-27",
    isDone: true,
  },
  {
    id: 3,
    title: "OOP Wonderland: Object-Oriented Programming",
    description: "Journey into the world of object-oriented programming",
    date: "2023-11-28",
    isDone: false,
  },
  {
    id: 4,
    title: "Git Mastery: Version Control Unleashed",
    description: "Navigate the realms of version control using Git",
    date: "2023-11-29",
    isDone: true,
  },
  {
    id: 5,
    title: "Web Wizardry: HTML and CSS",
    description: "Embark on a magical journey into web development",
    date: "2023-11-30",
    isDone: false,
  },
  {
    id: 6,
    title: "JavaScript Jamboree: Fundamentals Explored",
    description: "Dive deep into the enchanting world of JavaScript",
    date: "2023-12-01",
    isDone: true,
  },
  {
    id: 7,
    title: "Node.js Odyssey: Journey to the Backend",
    description: "Explore the backend with the power of Node.js",
    date: "2023-12-02",
    isDone: false,
  },
  {
    id: 8,
    title: "Database Chronicles: SQL and MongoDB",
    description: "Uncover the mysteries of databases with SQL and MongoDB",
    date: "2023-12-03",
    isDone: true,
  },
  {
    id: 9,
    title: "React Revolution: Building User Interfaces",
    description: "Join the revolution of building UIs with React",
    date: "2023-12-04",
    isDone: false,
  },
  {
    id: 10,
    title: "Redux Riddles: State Management Unleashed",
    description: "Solve the riddles of state management in React with Redux",
    date: "2023-12-05",
    isDone: true,
  },
  {
    id: 11,
    title: "API Adventures: RESTful Principles Explored",
    description: "Embark on thrilling adventures in API development",
    date: "2023-12-06",
    isDone: false,
  },
  {
    id: 12,
    title: "Testing Tales: Journey into Software Testing",
    description: "Explore the tales and challenges of software testing",
    date: "2023-12-07",
    isDone: true,
  },
  {
    id: 13,
    title: "Docker Dreams: Containerization Unveiled",
    description: "Dream the dream of containerization with Docker",
    date: "2023-12-08",
    isDone: false,
  },
  {
    id: 14,
    title: "Serverless Symphony: AWS Lambda Unleashed",
    description:
      "Experience the symphony of serverless architecture with AWS Lambda",
    date: "2023-12-09",
    isDone: true,
  },
  {
    id: 15,
    title: "CI/CD Finale: Continuous Integration/Continuous Deployment",
    description: "Conclude the journey with the grand finale of CI/CD",
    date: "2023-12-10",
    isDone: false,
  },
];
